[package]
name = "clingo"
version = "0.6.0"
authors = ["sthiele <sthiele78@gmail.com>"]
edition = "2018"
description = "Rust idiomatic bindings to the clingo library"
categories = ["api-bindings"]
license = "MIT"
repository = "https://github.com/potassco/clingo-rs"
documentation = "https://docs.rs/clingo"
readme = "README.md"
exclude = ["/.travis.yml"]

[badges]
travis-ci = { repository = "potassco/clingo-rs" }

[lib]
name = "clingo"
path = "src/lib.rs"

[features]
dynamic_linking = ["clingo-sys/dynamic_linking"]

# Provide derive(ToSymbol) macro.
derive = ["clingo-derive"]

[dependencies]
clingo-sys = { version = "0.6.0" }
clingo-derive = { version = "0.2.0", optional = true }
rand = "0.7"
thiserror = "1.0"
bitflags = "1.2"

[dev-dependencies]
trybuild = "1.0"
clingo-derive = { version = "0.2.0" }
